### ISSUE TITLE
Enhance GitHub Portfolio Page with Modern Features

### ISSUE THREAD

**Issue by Lasag123** [Lasag123/lasag123.github.io#1]
### Structure Improvements
1. Create a modern single-page layout with the following sections:
   - Hero section with your name and professional summary
   - About Me section
   - Skills & Technologies
   - Projects Showcase
   - Contact Information

### Projects Showcase Integration
1. Add a dynamic projects section using GitHub API:
```javascript
async function fetchGitHubProjects() {
    const username = 'Lasag123';
    const response = await fetch(`https://api.github.com/users/${username}/repos`);
    const projects = await response.json();
    return projects;
}
```

2. Create project cards with:
   - Repository name and description
   - Technologies used (based on repo languages)
   - Star count and fork count
   - Direct links to live demos and source code

### Modern Styling Recommendations
1. Use modern CSS features:
```css
:root {
    --primary-color: #0366d6;
    --background: #ffffff;
    --text: #24292e;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.project-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 2rem;
}

/* Add smooth transitions */
.project-card {
    transition: transform 0.2s ease;
}

.project-card:hover {
    transform: translateY(-5px);
}
```

2. Implement responsive design:
```css
@media (max-width: 768px) {
    *
